server:
  port: 31001
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  application:
    name: xc_service_manage_cms

#eureka:
#  server:
#    enable-self-preservation: false #是否开启自我保护模式
#    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
#  client:
#    registerWithEureka: true #服务注册开关
#    fetchRegistry: true #服务发现开关
#    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
#      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
#  instance:
#    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
#    ip-address: ${IP_ADDRESS:127.0.0.1}
#    instance-id: ${spring.application.name}:${server.port} #指定实例id