server:
  port: ${PORT:40400}
spring:
  application:
    name: xc_service_ucenter_auth
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/xc_user?characterEncoding=utf-8}
      username: root
      password: 185910
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  redis:
    host: ${REDIS_HOST:192.168.204.131}
    port: ${REDIS_PORT:6379}
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 2
        min-idle: 1
        max-wait: -1
    password: redis-pass
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    password: xuecheng
    alias: xckey
